import type { Metadata } from 'next'
import { Inter as FontSanster } from 'next/font/google'
import '@/shared/styles/globals.css'
import { cn } from '@/shared/lib/utils'

const fontSans = FontSanster({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          'flex items-center justify-center bg-primary font-sans antialiased ',
          fontSans.variable
        )}
      >
        <main className="container min-h-screen w-screen max-w-screen-sm bg-background">
          {children}
        </main>
      </body>
    </html>
  )
}
